### ISSUE TITLE
enhancement: merge source files

### ISSUE THREAD

**Issue by Darkein** [jaroslavsvak/xlf-merge#1]
Hello,

I would like to merge 2 source files, but unfortunately I have an error because there is no <target> inside a source file.
Do you think you could remove this verification?

Thanks!

**Comment by jaroslavsvak** [comment]
I have allowed XLF files without any trans-unit elements in version 1.04. The tool will still require xliff, file, and body elements. So something like this will be accepted now:

`<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="cs" datatype="plaintext" original="ng2.template">
    <body>
        
    </body>
  </file>
</xliff>`

Hope this solves the issue.

**Comment by Darkein** [comment]
Thanks, i try it asap :)

**Comment by Darkein** [comment]
hum, I didn't have errors because the name of my file was incorrect... But now I have the previous error about the target:
```
xlf-merge src/i18n/extracted.xlf src/i18n/externals.xlf -o src/i18n/messages.xlf
Initial file src/i18n/extracted.xlf
Error: Element /target not found. Make sure that the XLF file schema is correct. File name: src/i18n/externals.xlf.
    at fail (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\merge-xlf.js:3:15)
    at getElement (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\merge-xlf.js:19:17)
    at module.exports (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\merge-xlf.js:56:36)
    at runMerge (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\index.js:19:18)
    at Object.<anonymous> (C:\Users\pfior\Repos\visiotalent-v2\account\front\node_modules\xlf-merge\index.js:41:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

my extracted.xlf file:
```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="fr" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="keyDescription" datatype="html">
        <source>keyDescription</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/forms/form-edit/shared/evaluation-type/evaluation-type.service.ts</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```


and my externals.xlf file:
```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" 
    xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="fr" datatype="plaintext" original="database">
        <body>
            <trans-unit id="EVALUATION_TYPE.1_LABEL" datatype="html">
                <source>Général</source>
            </trans-unit>
        </body>
    </file>
</xliff>
```

It seems correct to me, maybe you could see something wrong?
btw, I have the 1.0.4 version

**Comment by Darkein** [comment]
hum, I didn't have errors because the name of my file was incorrect... But now I have the previous error about the target:
```
xlf-merge src/i18n/extracted.xlf src/i18n/externals.xlf -o src/i18n/messages.xlf
Initial file src/i18n/extracted.xlf
Error: Element /target not found. Make sure that the XLF file schema is correct. File name: src/i18n/externals.xlf.
    at fail (***\node_modules\xlf-merge\merge-xlf.js:3:15)
    at getElement (****\node_modules\xlf-merge\merge-xlf.js:19:17)
    at module.exports (****\node_modules\xlf-merge\merge-xlf.js:56:36)
    at runMerge (****\node_modules\xlf-merge\index.js:19:18)
    at Object.<anonymous> (****\node_modules\xlf-merge\index.js:41:5)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

my extracted.xlf file:
```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" xmlns="urn:oasis:names:tc:xliff:document:1.2">
  <file source-language="fr" datatype="plaintext" original="ng2.template">
    <body>
      <trans-unit id="keyDescription" datatype="html">
        <source>keyDescription</source>
        <context-group purpose="location">
          <context context-type="sourcefile">src/app/forms/form-edit/shared/evaluation-type/evaluation-type.service.ts</context>
          <context context-type="linenumber">1</context>
        </context-group>
      </trans-unit>
    </body>
  </file>
</xliff>
```


and my externals.xlf file:
```
<?xml version="1.0" encoding="UTF-8" ?>
<xliff version="1.2" 
    xmlns="urn:oasis:names:tc:xliff:document:1.2">
    <file source-language="fr" datatype="plaintext" original="database">
        <body>
            <trans-unit id="EVALUATION_TYPE.1_LABEL" datatype="html">
                <source>Général</source>
            </trans-unit>
        </body>
    </file>
</xliff>
```

It seems correct to me, maybe you could see something wrong?
btw, I have the 1.0.4 version

**Comment by jaroslavsvak** [comment]
Yes, I can see what's missing. XLF files contain no translations (source is the original text in HTML and target should be the translated text):

            <trans-unit id="EVALUATION_TYPE.1_LABEL" datatype="html">
                <source>Général</source>
                **<target>--- translated text comes here ---</target>**
            </trans-unit>

Then the context-group points to the original location in HTML for informational purposes. You can keep it or delete it. I usually remove the context-group as it has no functional meaning. The source element is actually no needed too but I keep it in my projects. So final and working format of all translations is this:

            <trans-unit id="EVALUATION_TYPE.1_LABEL" datatype="html">
                <source>Général</source>
                <target>--- translated text comes here ---</target>
            </trans-unit>

After you translate all texts, XLF-MERGE will accept the file. I let the tool fail when something is not translated to make sure that everything is in place before building the production version of the app.


I'd also like to give you few extra hints about XLF you might find useful.
You can embed HTML in <target> that lets you create formatted text in translation:

<target>Text &lt;Bold&gt; bla bla</target>

Angular expressions (aka interpolations) in HTML work too. Example:

      <trans-unit id="BankAccounts-IBAN" datatype="html">
        <source>Bank Account (IBAN) <x id="INTERPOLATION"/></source>
        <target>Pankkitilinumero <x id="INTERPOLATION"/> (IBAN)</target>
      </trans-unit>

Where the <x id="INTERPOLATION"/> is an Angular expression in the original HTML:
<div i18n="@@BankAccounts-IBAN">Bank Account (IBAN) {{ user.bankAccount }}</div>
