### ISSUE TITLE
Merging multiple files from different locations

### ISSUE THREAD

**Issue by turguthelvacioglu** [jaroslavsvak/xlf-merge#2]
Hello,
I'm trying to merge multiple xlf files into one file. If all of the source xlf files are located in the same directory, the xlf-merge works fine. But let's say I have sub-directories under the location which I set as input parameter to xlf-merge command, the command only merges the files which are located under the input parameter. It doesn't make any actions to the files which are located under sub-directories.

I have a directory structure like below;
src/localization/app/first.en.xlf
src/localization/app/second.en.xlf
src/localization/app/login/third.en.xlf

and I run the command below:
xlf-merge src/localization/app/*.en.xlf -o src/localization/messages.en.xlf

All I want is; find all the *.en.xlf files under app directory (including sub-directories) and merge these files into one xlf file which is "messages.en.xlf" under "src/localization/" directory.

Now It only merges the files under app directory only, doesn't include the files which are located under sub-directories of "app" directory. (Doesn't include the xlf file under the "login" folder.)

Can you please help me about this issue?

King Regards,
Turgut

**Comment by jaroslavsvak** [comment]
Use double star (**) to include all subdirectories recursively:
xlf-merge src/localization/app/**/*.en.xlf -o src/localization/messages.en.xlf

This works fine in Windows. Can't test other MacOS / Linux right now.
