### ISSUE TITLE
Calling push on 'undefined' when XLIFF file contains empty body

### ISSUE THREAD

**Issue by M4nuF** [jaroslavsvak/xlf-merge#6]
Hello,

when I try to merge with a file which has an empty body tag I get the following error:
`TypeError: Cannot read property 'push' of undefined`.

It seems to happen here:
https://github.com/jaroslavsvak/xlf-merge/blob/master/merge-xlf.js#L76

According to the XLF 1.2 spec the body may contain "Zero, one or more <group> , <trans-unit>, <bin-unit> elements, in any order." (http://docs.oasis-open.org/xliff/v1.2/os/xliff-core.html#Specs_Elem_Struct).

This happens because we auto-generate files from a library which might produce empty XLIFF files. Those files we try to merge to one afterwards.

Thanks for looking into this 👍

**Comment by jaroslavsvak** [comment]
Fixed in latest version xlf-merge@1.0.8
